soracom/soracom-cli

- README.md
I needed to add the following to my ~/.bash_profile in order to make the soracom-cli bash completion work:
if [ -f $(brew --prefix)/etc/bash_completion ]; then
. $(brew --prefix)/etc/bash_completion
fi
> Providing a fix for Mac OSX bash-completion errors

- scripts/build.sh
This PR partially reverts #9, as `goxc` and `go-assets-builder` are required to be able to run while building. We have them in our go.mod, but they are just downloaded as dependencies, not installed in $PATH. We need to explicitly install them by `go get`.
> get back required dependencies on wercker

- generators/cmd/predefined/profiles.go
A user gets `unexpected newline` error when the user input nothing and just press Enter after seeing the prompt `(Y/n)`. This is not an expected behavior. This is caused by using `fmt.Scanf()`.
We can avoid this issue by using `ReadString()` of `bufio.Reader`.
---
`(Y/n)` というプロンプトのあとでユーザーが何も入力せずに Enter だけを押すと `unexpected newline` というエラーが発生してしまいます。これは期待される動作ではありません。
これは `fmt.Scanf()` を使っているために起こります。
`bufio.Reader` の `ReadString()` を用いることでこの問題を回避することができます。
> fix `unexpected newline` issue

- generators/cmd/predefined/configure_sandbox.go
- generators/cmd/predefined/profiles.go
This PR fixes the issue that if a user run `soracom configure-sandbox` interactively (i.e. without authentication parameters), the specified value of `--register-payment-method` is not used and its default value was `false`, the user is never able to specify it as `true`.
The default value for `--register-payment-method` option is now `true` to suit to `/v1/sandbox/init` API's specification. Users are still able to explicitly specify `--register-payment-method` explicitly to false, if they want to do.
---
`soracom configure-sandbox` をインタラクティブに（すなわち認証用の引数なしで）実行したときに `--register-payment-method` の値が使われず、しかもデフォルトが `false` でしたので、`true` にすることができないという問題を修正しました。
`/v1/sandbox/init` API の仕様に合わせデフォルトを `true` としました。`false` にしたければ明示的に指定することもできます。
> let register-payment-method be true by defalut for sandbox

- generators/cmd/templates/leaf.gotmpl
- generators/cmd/templates/root.gotmpl
- test/data/help_en_expected.txt
- test/data/help_ja_expected.txt
Added `--raw-output` global option to workaround the unwanted behavior that `&` is escaped in URLs.
Actually we already have a special treatment only for the output for `/v1/files/{scope}/{path}` API which is possibly returning binary files (it's done by .ResponseBodyRaw template variable). By this change, users will be able to explicitly specify the behavior for other APIs.
> add `--raw-output` option

- generators/assets/soracom-api.en.yaml
- generators/assets/soracom-api.ja.yaml
Add API definitions for Harvest Files prefix match listing
This patch adds the API definitions for listing Harvest Files entries
with the prefix match introduced as GET
/v1/files?scope=${scope}&prefix=${prefix}, which corresponding
subcommand is "files find".
> Support Harvest Files prefix match

- .github/workflows/build-artifacts.yml
- Makefile
- build/build.sh
- generators/cmd/predefined/lang_utils.go
- generators/lib/apidef_loader.go
- generators/lib/fileperm.go
- generators/lib/printer.go
- soracom/generated/cmd/lang_utils.go
This PR includes following changes:
- codes scattered around build scripts and GitHub Actions are aggregated into Makefile
- fix lint issues by adding comments for exported functions
- run lint and collect code complexity metrics just as goreportcard does
> enhancement: aggregate build commands into Makefile

- build/Dockerfile
`latest` is mutable and that would point to various targets; the actual target where it points is dependent on the executor's environment because of the local cache.
I've encountered an error like the following:
```
github.com/soracom/soracom-cli/generators/cmd/predefined imports
embed: package embed is not in GOROOT (/usr/local/go/src/embed)
make: *** [Makefile:30: install-deps] Error 1
```
because I have had the local cache that associates with `latest` that contains OLD go runtime.
> Specify the golang runtime version in a Dockerfile

- generators/assets/soracom-api.en.yaml
- generators/assets/soracom-api.ja.yaml
- go.mod
- go.sum
- soracom/generated/cmd/assets/soracom-api.en.yaml
- soracom/generated/cmd/assets/soracom-api.ja.yaml
- soracom/generated/cmd/sigfox_devices_terminate.go
Curerntly Sigfox devices are deleted in twenty four hours after they are
terminated. However, we learned in some cases operators want to delete
them immediately. For instance, the user that has multiple operators
might want to transfer Sigfox devices between those operators. In that
case they might not want to wait for twenty four hours and register
their Sigfox devices for an operator right after terminating the devices
that were owned another operator.
To enable immediate deletion of the Sigfox devices, --delete-immediately
option is added for "sigfox-devices terminate" subcommand. This
immediately deletes the Sigfox device and its PAC is given in the
response. Note it is the responsibility of the operator to keep the PAC
with them.
Signed-off-by: Taku Fukushima <taku@soracom.jp>
> Add --delete-immediately option to "sigfox-devices terminate"

- build/Dockerfile
Docker hub の公式イメージはときどき rate limit に引っかかって、soracom-cli をビルドして利用している他のリポジトリの CI などが失敗することがあるので、rate limit の上限の大きな ECR 上のイメージを使うことにしました。
bitnami の提供するイメージですが、一応 Verified アカウントのようですので大丈夫だと思います。
バージョン指定は latest にしてしまいましたが、特定のバージョンに固定したほうが良いでしょうか？
> use a public image on ECR Public Gallery to avoid docker hub rate limit

- generators/cmd/predefined/configure_sandbox.go
- soracom/generated/cmd/configure_sandbox.go
これまで `profile` 型をそのまま JSON にして `/v1/sandbox/init` API に渡していましたが、`profile` 型では `coverageType` という `string` 型を保持しているのに対し `/v1/sandbox/init` API は `coverageTypes` という文字列型の配列を受け取る仕様になっており、ここが食い違っていて coverageType を指定していないことになってしまっていましたので修正しました。
> fix request body for /v1/sandbox/init api

- snap/release.sh
`snapcraft` コマンドのサブコマンド `push` を使用しているところで `upload` に変更するようにという warning が出たのでその対応です。
> update `snapcraft push` to `snapcraft upload`

- test/test.sh
認証情報をコマンドラインから指定する場合は coverage type も指定しないといけなかったので修正しました。
> fix test script to specify coverage type explicitly

- generators/cmd/predefined/check_param.go
- soracom/generated/cmd/check_param.go
https://soracom.slack.com/archives/C03K32D6W/p1639958820481600
こちらで makoto に指摘された件の修正です。
> SORACOM CLI でエラーメッセージに {{.LongOption}} と表示されるケースを発見しました。
> ```
> $ soracom stats air get --imsi 440103213043029 --period month
> Error: required parameter '{{.LongOption}}' is not specified
> ```
> fix to use option name

- generators/assets/cli/en.yaml
- generators/assets/cli/ja.yaml
- soracom/generated/cmd/assets/cli/en.yaml
- soracom/generated/cmd/assets/cli/ja.yaml
`configure-sandbox` コマンドの CLI ヘルプの文言が不足していたり識別子が誤っていて利用されていなかったので修正です。
> fix text resources for cli

- README.md
- README_ja.md
- install.sh
According to the discussions, we came to the conclusions that we should provide a one-liner command to install soracom-cli without package managers.
After merging this PR to master, users can install soracom-cli by executing the following command:
```
curl -fsSL https://raw.githubusercontent.com/soracom/soracom-cli/master/install.sh | bash
```
> add a script to install soracom-cli to /usr/local/bin

- .github/workflows/build-artifacts.yml
- build/Dockerfile
Go のバージョンを現時点の安定版の最新である 1.17.8 に更新しました
> update golang version

- snap/build.sh
snap でインストールした soracom コマンドはデフォルトでは Sandbox に閉じ込められており `$SNAP_USER_DATA`（すなわち `$HOME/snap/soracom/<revision>/`）以下のディレクトリのファイルしか読み書きすることができません。
そこでユーザーに明示的にその制約を解除してもらった場合に `$HOME/.soracom` のみ読み書きできるようにするための変更です。
> add snap plug to be able to access user's $HOME/.soracom

- generators/cmd/predefined/apiclient.go
- generators/cmd/predefined/apiclient_test.go
- soracom/generated/cmd/apiclient.go
- soracom/generated/cmd/apiclient_test.go
Do not dump X-Soracom-Api-Key and X-Soracom-Token even when SORACOM_VERBOSE is set.
This PR will replace header values of both `X-Soracom-Api-Key` and `X-Soracom-Token` to `<hidden>` from HTTP request
Fixes #64 
None
No
> hide secure headers from HTTP request

- generators/cmd/predefined/apiclient.go
- generators/cmd/predefined/apiclient_test.go
- generators/cmd/predefined/pretty_print_json.go
- soracom/generated/cmd/apiclient.go
- soracom/generated/cmd/apiclient_test.go
- soracom/generated/cmd/pretty_print_json.go
soracom-cli の出力する JSON は、文字列中に `&` `<` および `>` が含まれるとそれらをエスケープして `\u0026` `\u003c` および `\u003e` に変換しています。これは Go の `json` パッケージの `Marshal()` 関数の [仕様](https://pkg.go.dev/encoding/json#Marshal) によるものです。
この仕様は元々、Marshal して生成した JSON を HTML の中に埋め込む際に安全なように、ということでデフォルトでエスケープするようになっているようです。
soracom-cli の出力をそのまま HTML に埋め込むことは考えづらいのでセキュリティ問題には直接的には繋がりにくいであろうことと、SORACOM API の各種 Export 系の API が返してくる AWS S3 の Pre-signed URL に含まれる `&` が `\u0026` に変換されてしまうとその URL は無効でありアクセスできないという問題がありますがそれが回避できるという利便性があることから、自動的にエスケープしないようにしました。
何か懸念がございましたらお知らせください。
> avoid '&', '<' and '>' from escaping while marshaling to json

- generators/cmd/src/gen_leaf_cmd.go
- generators/cmd/templates/leaf.gotmpl
- go.mod
- go.sum
- soracom/generated/cmd/lagoon_migration_migrate.go
- soracom/generated/cmd/lora_network_sets_create.go
- soracom/generated/cmd/sandbox_init.go
- soracom/generated/cmd/sandbox_subscribers_create.go
- soracom/generated/cmd/subscribers_issue_transfer_token.go
- soracom/generated/cmd/system_notifications_set.go
リクエスト Body の JSON のトップレベルの要素は `--body` を使わなくてもコマンドライン引数で直接指定することができるという機能がありますが、文字列の配列には対応していなかったので対応させました。
たとえば、`soracom system-notifications set` コマンドは Body に以下のような引数を指定できますが、
```
{
"emailIdList": ["foo@example.com", "bar@example.com"],
"password": "P@$$w0rd",
}
```
従来は `password` のみ `soracom` コマンドに引数として直接指定することができ、`emailIdList` は `--body` 引数として JSON 形式で指定する必要がありました:
```
soracom system-notifications set --type primary --password "$password" --body "{\"emailIdList\":[\"foo@example.com\",\"bar@example.com\"]}"
```
今回の変更により、
```
soracom system-notifications set --type primary --password "$password" --email-id-list "foo@example.com" --email-id-list "bar@example.com"
```
というふうに指定できるようになりました。
ついでに軽くリファクタリングを行ったので変更量がすこし多くなってしまいました :bow:
> support string slice parameters in request body

- build/build.sh
お世話になっております。
メカトラックス株式会社の清永と申します。
現在、弊社リポジトリ（mechatrax.github.io）にて御社の soracom-cli を再配布しております。
誠に勝手ではございますが、ビルドするパッケージにライセンスを含めるよう変更していただくことは可能でしょうか。
お忙しいところ恐れ入りますが、ご検討のほど宜しくお願いいたします。
> Include License in package

- test/find_unprovided_text_resources.sh
CLI 固有のテキストリソース（`cli.` で始まる）を追加し忘れている箇所を見つけるためのスクリプトを作成しました。
こちらのスクリプトですでに不足しているリソースをいくつか発見しており、修正が必要ですが、それは別 PR としたいと思います。
また、今後 GitHub Actions でこのスクリプトを実行するようにしたいと考えていますが、それも別 PR として、当 PR ではとりあえずスクリプトだけまずは追加します。
> Add tool to find unprovided text resources

- test/find_unprovided_text_resources.sh
スクリプトに未使用の変数があって shellcheck に引っかかり build.sh が通らなくなっていたので未使用の変数を削除します。
> remove unused vars
